services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    network_mode: bridge 	
  client:
    container_name: client
    build: ./client
    ports:
      - "8000:8000"
    network_mode: bridge
